-- ------------------------------
-- desc: generated by xls2data.py
-- source: 场景加载配置表.xls
-- sheet: 场景加载配置表
-- ------------------------------


Data = {
	['gameScene'] = {
		['path'] = '',--'Assets/Scenes/s001/s001.unity',
		['level'] = 's001',
	},
	['betScene'] = {
		['path'] = '',
		['level'] = 'bet',
	},
	['loginScene'] = {
		['path'] = '',
		['level'] = 'login',
	},
	['mainCity1'] = {
		['path'] = 'Assets/Scenes/s00001/s00001.unity',
		['level'] = 's00001',
	},
	['fightScene1'] = {
		['path'] = 'Assets/Scenes/s00001/s00001.unity',
		['level'] = 's00001',
	},
}
